### ISSUE TITLE
the converted model get more larger

### ISSUE THREAD

**Issue by niliusha123** [jianghaojun/CondenseNetV2#2]
hi，thanks for your best contributions!
When i converted the trained model on cifar10, i find the converted model get more larger,e.g. 10723->24418, how can i converted the model right, or the fact is that.

the train arguments on cifar10 is :
--model condensenetv2 -b 64 -j 12 --data cifar10 --stages 14-14-14 --growth 8-16-32

thanks!

**Comment by jianghaojun** [comment]
Did you use this [function](https://github.com/jianghaojun/CondenseNetV2/blob/c771957cb8fe466d0ecbafe9060e4c342a33fc4d/utils/tools.py#L32) to convert your model?

**Comment by niliusha123** [comment]
yes,i did, 
and i tried to converted the model by convert_and_eval.py on cifar10, the result is same.
and then i tried to replace the function of CondensingSFR in layers.py to CondensingConv in projects Condensenet，the models got smaller，but it got wrongs when test. 
what i think the question of the converted models get larger is in  the function of CondensingSFR, would you please have a see.
thanks

**Comment by jianghaojun** [comment]
I test the model configuration which you provide.

The original model's FLOPs/Parameters are 203.17M/1.49M. After converting, the model's FLOPs/Param will be 40.60M/1.22M which are less than original model. 

Could you give model details about your experiments? For example, what is the meaning of the number 10723->24418?

**Comment by niliusha123** [comment]
oh，the 10723KB means the param of models  that convert to onnx，and the 24418KB means the param of converted models that converted to onnx.
could you please give me your email, then i send my codes to you

**Comment by jianghaojun** [comment]
To be honest, we do not test what will happen if we convert the pytorch model to onnx model. Our experiments are all conducted on GPU device.  You can send your code to my email(jhj20@mails.tsinghua.edu.cn), I will check your code later(project ddl is coming, sorry) see what I can do to help you.

**Comment by niliusha123** [comment]
OK, thanks
i will send my projects to you, and  the converted model on GPU device is also get larger, so i will hope you help me solve the problem,
