### ISSUE TITLE
Pre-trained weight

### ISSUE THREAD

**Issue by TomHsu-MIddle** [jianghaojun/CondenseNetV2#4]
![image](https://user-images.githubusercontent.com/69625741/128133176-05070f94-87b1-416c-9067-67ebd9f1ecde.png)
Is it only include weights or it is full model and weights?

**Comment by jianghaojun** [comment]
It is the model weights after converting the each SFR module to a standard group convolution.

You can test the provided model following:
`python test.py --model converted_cdnv2_a/b/c \
  --data_url /PATH/TO/IMAGENET -b 32 -j 8 \
  --train_url /PATH/TO/LOG_DIR \
  --evaluate_from /PATH/TO/MODEL_WEIGHT`
