### ISSUE TITLE
Pruning issue

### ISSUE THREAD

**Issue by fushh** [jianghaojun/CondenseNetV2#5]
Awesome job!
Recently, I have read your paper and have a question about the way you prune the weight. In the paper, you write as following

> M^g_{i,j} is set to zero for all j in g-th group for each pruned output feature map i.

Maybe it should be implemented as 
`self._mask[d, i:i+d_in, :, :].fill_(0)`
rather than
https://github.com/jianghaojun/CondenseNetV2/blob/c771957cb8fe466d0ecbafe9060e4c342a33fc4d/utils/layers.py#L247

Is there anything wrong of my understanding?

**Comment by jianghaojun** [comment]
Thanks for your attention. We implement the **Shuffle Operation**[1] between each group inside the mask. The **Shuffle Operation** is mentioned in section 3.2 architecture design.

[[1]ShuffleNet: An Extremely Efficient Convolutional Neural Network for Mobile Devices](https://arxiv.org/abs/1707.01083)

**Comment by fushh** [comment]
你好，你的邮件付盛豪已经收到啦，会尽快处理哒~
