### ISSUE TITLE
issue about SFR-ShuffleNetV2

### ISSUE THREAD

**Issue by Piplebobble** [jianghaojun/CondenseNetV2#6]
Sfr-shufflenetv2 is mentioned in the paper, but I can't find its code. Is Sfr-shufflenetv2 add or concat 1 * 1 convolution and the other half channel of the input?
And the paper mentioned that you shuffle the channel after using the SFR module in condensenetv2, but I didn't see the use of channel shuffle in the corresponding condensenetv2.py file, so channel shuffle is not necessary, right? thanks!!

**Comment by jianghaojun** [comment]
In shufflenetv2, the input for each block is splited into two part, one is go through conv (output p1) and concat with another unprocessed part(p2). We just use our sfr module to generate update information from the p1 and add the update information on p2.
