### ISSUE TITLE
训练时，imagenet数据集结构是怎样的呢？

### ISSUE THREAD

**Issue by Zhangwt95** [jianghaojun/CondenseNetV2#7]
您好，我看源代码中参考Pytorch Image Models的代码，但是数据集训练的代码有所修改。请问训练时，关于imagenet数据集的文件结构以及目录是怎样的呢？标签文件怎么放置？

**Comment by jianghaojun** [comment]
The file structure is shown below:

 -train
&nbsp;-n07711569
&nbsp;&nbsp;-n07711569_998.JPEG
&nbsp;&nbsp;-n07711569_9869.JPEG
&nbsp;&nbsp;-...
&nbsp;-n07697537
&nbsp;- ...
 
 -val
&nbsp;-n07711569
&nbsp;&nbsp;-ILSVRC2012_val_00000183.JPEG
&nbsp;&nbsp;-ILSVRC2012_val_00000406.JPEG
&nbsp;&nbsp;-...
&nbsp;-n07697537
&nbsp;- ...
