### ISSUE TITLE
Weight size mismatch between the pretrained model and the model defined in the code！预训练模型和代码中的模型参数尺寸不匹配

### ISSUE THREAD

**Issue by chenhao12** [jianghaojun/CondenseNetV2#8]
size mismatch for features.denseblock_1.denselayer_1.conv_1.conv.weight: copying a param with shape torch.Size([32, 2, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 16, 1, 1]).

**Comment by jianghaojun** [comment]
Could you please provide more informations, such as which model and which code file you used?
